<?php
namespace app\admin\controller;

use app\common\controller\AdminController;

use app\common\model\BookWriteChapter;

class BookWrite extends AdminController
{

    protected $modelClass = 'app\common\model\BookWrite';
    protected $validate = [
        ['name|书名','require|max:30'],
        ['author|作者','require|max:10'],
        ['content|最新章节','require'],
    ];

    protected function findModel($id)
    {
        $m = parent::findModel($id); // TODO: Change the autogenerated stub
        $m->chapter;
        $m->new_chapter;
        return $m;
    }

    protected function prepareDataProvider()
    {
        $list = parent::prepareDataProvider(); // TODO: Change the autogenerated stub
        foreach ($list as $m){
            $m->new_chapter;
        }
        return $list;
    }


    /**
     * 发布著书
     * @return string
     */
    public function save()
    {

        //验证
        $result = $this->validate($_POST,$this->validate);

        if (true !== $result) {
            return $this->error($result);
        }

        $modelClass = $this->modelClass;
        $model = new $modelClass($_POST);
        // 过滤post数组中的非数据表字段数据
        $model->allowField(true)->save();
        if($model){

            $file = request()->file('cover_img');
            $coverImg = $this->uploadToAlyun($file);

            $model->cover = $coverImg;
            $model->save();
            $model->chapter()->save(['content'=>$_POST['content'],'sequence'=>1]);
            $this->success("著书发布成功！","index");

        }else{
            $this->error("发布著书失败！");
        }

    }

    /**
     * 更新著书
     * @return string
     */
    public function update($id)
    {

        //验证
        $result = $this->validate($_POST,$this->validate);

        if (true !== $result) {
            return $this->error($result);
        }

        $model = $this->findModel($id);
        if($model){
            $params = request()->param();
            $file = request()->file('cover_img');
            if($file){
                $coverImg = $this->uploadToAlyun($file);
                $params['cover'] = $coverImg;
            }

            $rt = $model->allowField(true)->save($params);
            if($params['chapter_id']){
                $chapter = BookWriteChapter::get($params['chapter_id']);
                if($chapter==null)$this->error("该章节不存在！");
                $rt = $chapter->allowField(true)->save($params);
                $this->success("更新成功!","index");
            }
            if($model->new_chapter){
                $newSequence = $model->new_chapter->sequence+1;
            }else{
                $newSequence = 1;
            }
            $rt2 = $model->chapter()->save(['title'=>$_POST['title'],'content'=>$_POST['content'],'sequence'=>$newSequence]);
            if($rt||$rt2){
                $this->success("更新成功！","index");
            }else{
                $this->error("更新失败!");
            }

        }else{
            $this->error("该著书不存在！");
        }

    }
}
