<?php
namespace app\admin\controller;

use common\controller\AdminController;

use common\model\Admin as AdminModel;
use common\model\BookHouse as BookHouseModel;
use common\model\Category as CategoryModel;

class BookHouse extends AdminController
{

    protected $modelClass = 'common\model\BookHouse';
    //public $condition = '';

//    //查
//    public function index()
//    {
//        return "index";
//    }
//
//    public function read($id){
//        return "read";
//    }
//
    //增
    public function create(){
        $list = AdminModel::all(['type'=>3]);
        $this->assign('list',$list);
        return $this->fetch();
    }
//
//    public function save()
//    {
//        return "sava";
//    }
//
    //改
    public function edit($id)
    {
        $list = AdminModel::all(['type'=>3]);
        $this->assign('list',$list);
        return parent::edit($id); // TODO: Change the autogenerated stub
    }
//
//    public function update($id){
//        return "update";
//    }
//
//    //删
//    public function delete($id){
//        return "delete";
//    }



    /**
     * 书屋列表
     * @return mixed
     */
    public function houseList(){

        $list = BookHouseModel::all();
        $this->assign('list',$list);
        return $this->fetch();
    }

    public function add(){
        $typeList = RoomCategoryModel::all();
        $this->assign('typeList',$typeList);
        return $this->fetch();
    }

    /**
     * 添加信息
     */
    public function doAdd(){

        $house = new HouseModel();
        $house->allowField(true)->data(request()->param(),true);
        $house->create_time = time();
        $house->save();

        //关联图片
        $files = request()->file('image');
        $picList = array();

        foreach($files as $key=>$file){

            $info = $file->move(ROOT_PATH . 'public' . DS . 'uploads');
            $filePath =$info->getSaveName();

            if($info){

                $url = str_replace('\\','/',$filePath);
                $status = count($picList)==0?1:0;//如果是第一个添加的元素就设置为1，其他为0

                $picList[] = [
                    'url'=>$url,
                    'house_id'=>$house->id,
                    'ismain'=>$status
                ];


            }else{
                // 上传失败获取错误信息
                echo $file->getError();
            }

            usleep(100);

        }
        $house->img()->saveAll($picList);


//        // 关联sku
//        $sku_name = request()->param()['sku_name'];
//        $sku_price = request()->param()['sku_price'];
//        $sku_stock = request()->param()['sku_stock'];
//        $skuList = array();
//        foreach($sku_name as $key=>$name){
//            //用下标来输入其他两个数组的信息
//            $skuList[]=[
//                'name'=>$name,
//                'price'=>$sku_price[$key],
//                'stock'=>$sku_stock[$key]
//            ];
//        }
//
//        $hotel->sku()->saveAll($skuList);

        if($house->id){
            $this->success('添加成功','/admin/house/getList');
        }else{
            $this->error('名宿添加失败！');
        }

    }


    public function doEdit($id){

    }


}
