<?php
namespace app\admin\controller;

use app\common\controller\AdminController;


use think\Request;

class BookRent extends AdminController
{

    protected $modelClass = 'app\common\model\BookRent';
    protected $order = 'rent_time DESC';

    protected function prepareDataProvider()
    {
        $type = Request::instance()->get('type');
        $this->assign('type',$type);
        if($type!=null){
            $this->condition['status'] = $type;
        }
        $list = parent::prepareDataProvider(); // TODO: Change the autogenerated stub
        foreach ($list as $m){
            $m->book;
            if($m->book){
                $m->book->model;
            }
        }
        return $list;
    }

}
