<?php
namespace app\admin\controller;

use common\controller\AdminController;

use common\model\Book as BookModel;
use common\model\BookHouse as BookHouseModel;
use common\model\BookModel as BookModelModel;
use common\model\Category as CategoryModel;
use think\Request;

class ErrorLog extends AdminController
{

    protected $modelClass = 'common\model\ErrorLog';
    protected $order = 'create_time desc';

    protected function prepareDataProvider()
    {
        $type = Request::instance()->get('type');
        $this->assign('type',$type);
        if($type){
            $this->condition = ['type'=>$type];
        }
        return parent::prepareDataProvider(); // TODO: Change the autogenerated stub
    }
}
