<?php
namespace app\admin\controller;

use app\common\controller\AdminController;

use think\Request;

class ErrorLog extends AdminController
{

    protected $modelClass = 'app\common\model\ErrorLog';
    protected $order = 'create_time desc';

    protected function prepareDataProvider()
    {
        $type = Request::instance()->get('type');
        $this->assign('type',$type);
        if($type){
            $this->condition = ['type'=>$type];
        }
        return parent::prepareDataProvider(); // TODO: Change the autogenerated stub
    }
}
