<?php
namespace app\admin\controller;

use app\common\controller\AdminController;
use app\common\model\Hotel as HotelModel;
use app\common\model\HotelSupportFacility as SupportFacilityModel;

class Hotel extends AdminController
{

    protected $modelClass = 'app\common\model\Hotel';
    protected $beforeActionList = [
        'htmlVariable'  =>  ['only'=>'create,edit'],
    ];

    public function _initialize()
    {
        parent::_initialize();
        $type = input('get.type');
        if($type !== null){
            $this->condition['status'] = $type;
        }
        $this->setAssign(['type'=>$type]);
    }

    /**
     * 模板变量
     */
    protected function htmlVariable(){
        $supportFacility = SupportFacilityModel::all();
        $this->setAssign(['supportFacility'=>$supportFacility]);
    }

    /**
     * find model
     * @param $id
     * @return string
     */
    protected function findModel($id){
        $m = parent::findModel($id);
        $m->img;
        $m->room;
        $m->support;
        $m->comment;
        return $m;
    }

    protected function prepareDataProvider()
    {
        if($this->admin->role!=1){
            $this->condition['owner_id'] = $this->admin->id;
        }
        return parent::prepareDataProvider(); // TODO: Change the autogenerated stub
    }


    /**
     * 添加信息
     */
    public function doAdd(){
        $params = request()->param();
        $house = new HotelModel();
        $house->allowField(true)->data($params,true);
        $house->create_time = time();
        $house->save();

        //关联图片
        $files = request()->file('image');
        $picList = array();

        foreach($files as $key=>$file){

            $picUrl =$this->uploadToAlyun($file);

            if($picUrl){
                $status = count($picList)==0?1:0;//如果是第一个添加的元素就设置为1，其他为0
                //保存缩略图
                if($key==0){
                    $house->thumb = $picUrl;
                    $house->save();
                }

                $picList[] = [
                    'url'=>$picUrl,
                    'hotel_id'=>$house->id,
                    'ismain'=>$status
                ];


            }else{
                // 上传失败获取错误信息
                echo $file->getError();
            }

            usleep(100);

        }
        $house->img()->saveAll($picList);
        $house->support()->saveAll($params['support']);

        if($house->id){
            $this->success('添加成功','index');
        }else{
            $this->error('名宿添加失败！');
        }

    }

    /**
     * 确认修改
     * @param $id
     * @return string
     */
    public function update($id){
        $params = request()->param();
        $house = HotelModel::get($id);
        if(!$house){
            $this->error('你的思想有点漂浮哦，系统完全跟不上！');
        }
        $house->allowField(true)->data(request()->param(),true);
        $house->create_time = time();
        $house->save();

        //关联图片
        $files = request()->file('image');

        if($files){
            $picList = array();
            foreach($files as $key=>$file){

                $picUrl =$this->uploadToAlyun($file);

                if($picUrl){

                    $status = count($picList)==0?1:0;//如果是第一个添加的元素就设置为1，其他为0
                    //保存缩略图
                    if($key==0){
                        $house->thumb = $picUrl;
                        $house->save();
                    }

                    $picList[] = [
                        'url'=>$picUrl,
                        'hotel_id'=>$house->id,
                        'ismain'=>$status
                    ];

                }else{
                    // 上传失败获取错误信息
                    echo $file->getError();
                }

            }
            $house->img()->saveAll($picList);
        }

        if(isset($params['support'])){
            $house->support()->detach();
            $house->support()->saveAll($params['support']);
        }

        if($house->id){
            $this->success('修改成功！','index');
        }else{
            $this->error('修改失败！');
        }
    }

    /**
     * 开启、关闭营业
     */
    public function toggle($id){
        $model = $this->findModel($id);
        if($model==null) return json(['code'=>0,'msg'=>'该民宿不存在！']);
        $rt = $model->allowField(true)->save(request()->param());
        if($rt){
            return json(['code'=>100]);
        }else{
           return json(['code'=>0,'msg'=>'操作失败！']);
        }

    }
}
