<?php
namespace app\admin\controller;

use common\controller\AdminController;
use think\Request;

class Order extends AdminController
{

    protected $modelClass = 'common\model\Order';
    protected $order = 'create_time DESC';

    protected $beforeActionList = [
        'preposition'  =>  ['only'=>'index,create,save,edit,update,delete'],
    ];

    /**
     * 前置操作
     */
    protected function  preposition(){
        $type = paramFromGet('type');
        if($type!=null){
            $this->condition = ['status'=>$type];
        }
        $this->setAssign(['type'=>$type]);
    }


    protected function prepareDataProvider()
    {
        $list =  parent::prepareDataProvider(); // TODO: Change the autogenerated stub
        foreach ($list as $m){
            $m->item;
        }
        return $list;
    }

}
